services:
  - type: web
    name: mobile-store-backend-new
    runtime: docker
    plan: free
    branch: main
    repo: https://github.com/Noori-Senior/mobile-store-backend-new
    buildFilter:
      paths:
        - Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: nozomi.proxy.rlwy.net
      - key: DB_PORT
        value: 58266
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: ttKJsBoZvKViKwwODuPvfHTyOQFlqfwI
