services:
  - type: web
    name: mobile-store-backend
    runtime: docker
    plan: free
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: "10417"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: DYmSAuYDhoNxeftakeIzHDKFBtFPyZdV
